FROM node:25-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY frontend/package.json frontend/package-lock.json ./frontend/
RUN cd frontend && npm ci

COPY backend/package.json backend/package-lock.json ./backend/
RUN cd backend && npm ci

COPY cypress ./cypress
COPY cypress.config.js .
COPY frontend/src ./frontend/src
COPY frontend/test ./frontend/test
COPY frontend/index.html ./frontend/index.html
COPY frontend/vite.config.js ./frontend/vite.config.js
COPY backend/. ./backend/
